routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/', 'HomeController@index')->name('home');

//Api Ajax
Route::post('/api/vehicles/count', 'ApiController@getNbOfVehicles');
Route::post('/api/vehicles/estim', 'ApiController@estimVehicles');
Route::post('/api/vehicles/formulaires', 'ApiController@formulaires');
Route::get('/api/brand/byType/{type}/{neuf}', 'ApiController@brandByType');
Route::post('/api/comments/store', 'CommentController@store');
Route::get('/api/comments/exprension/{exp}/{id}', 'CommentController@exprension');
Route::get('/api/vehicles/comparateurVehicles/{model}', 'ApiController@getcomparateurVehicles');

//Search Routes
Route::post('/search/searchNeuf', "searchController@searchNeuf");
Route::post('/search/guide_search', "searchController@searchNeuf");
Route::post('/search/searchOccasion', "searchController@searchOccasion");
Route::get('/search/searchOccasion', "searchController@searchOccasion"); // pagination
Route::get('/search/neuf/{brand}', "searchController@searchNeufBrand");
Route::get('/search/neuf/{brand}/{model}', "searchController@searchNeufModel");
Route::get('/search/searchDetailed', "searchController@searchDetailed");
Route::get('/search/searchDetailedOccasion', "searchController@searchDetailedOccasion");

//Routes Neuf
Route::get('/neuf', 'NeufController@index');
Route::post('/neuf/comparateur', 'NeufController@comparateur');
Route::get('/neuf/{brand}', 'NeufController@brand');
Route::get('/neuf/{brand}/{model}', 'NeufController@model');
Route::get('/neuf/{brand}/{model}/{version}', 'NeufController@version');

//Route Occasion
Route::get('/occasion', 'OccasionController@index');
Route::get('/occasion/annonce/{{id}}', 'OccasionController@index');

//Route Partenaire
Route::resource('/partenaires', 'PartenaireController');

//Route Video
Route::get('/videos', 'VideoController@allVideos');
Route::get('/videos/brand/{brandname}', 'VideoController@videosBySelect');
Route::get('/videos/{id}', 'ArticleController@show');

//Routes article
Route::get('/articles', 'ArticleController@allArticles');
Route::get('/articles/cat/{catname}', 'ArticleController@articlesByCat');
Route::get('/articles/{id}', 'ArticleController@showArticle');

// Routes administration
Route::resource('/administration/video', 'VideoController');
Route::resource('/administration/article', 'ArticleController');
Route::resource('/administration/brand', 'BrandController');
Route::resource('/administration/model', 'ModeleController');

Route::get('/administration/comment', 'CommentController@index');
//Route::get('/administration/comment/cmntSupp', 'CommentController@cmntSupp');
Route::get('/administration/comment/accepter/{id}', 'CommentController@accepter');
Route::get('/administration/comment/supprimer/{id}', 'CommentController@destroy');
Route::get('/administration/active/{id}/finished', 'UserController@active');

Route::resource('/administration/categorie', 'CategorieArticleController');
Route::resource('/administration', 'UserController');

resources/views/administration/create.blade.php
@extends('home')

@section('content')
<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" align="center">Create new user</div>
                        <div class="card-body">
                            @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                    @foreach($errors->all() as $error)
                                    <li>{{$error}}</li>
                                    @endforeach
                                    </ul>
                                </div>
                            @endif
                            @if(\Session::has('success'))
                                <div class="alert alert-success">
                                    <p>{{ \Session::get('success') }}</p>
                                </div>
                            @endif

    <form method="post" action="{{action('UserController@store')}}">
    {{ csrf_field() }}
        <div class="form-group">
            <input type="text" name="username" class="form-control" placeholder="Enter username" />
        </div>
        <div class="form-group">
            <input type="email" name="email" class="form-control" placeholder="Enter email" />
        </div>
        <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="Enter password" />
        </div>
        <div class="form-group">
            <input type="text" name="first_name" class="form-control" placeholder="Enter first name" />
        </div>
        <div class="form-group">
            <input type="text" name="last_name" class="form-control" placeholder="Enter last name" />
        </div>
        <div class="form-group">
            <input type="text" name="phone_number" class="form-control" placeholder="Enter phone number" />
        </div>
        <div class="form-group">
            <input type="text" name="type" class="form-control" placeholder="Type" />
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" />
        </div>
    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/administration/edit.blade.php
@extends('layouts.app')
@section('style')
<style>
    .form-group{
        margin-top: 10px;
    }  
    .form-control{
        margin-top: 5px;
    } 
    label{
        margin-bottom: 5px;
    }
</style>
@endsection
@section('content')
<div class="container mt-4 mb-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" align="center">Modifier les informations de l'utilisateur</div>
    
                    <div class="card-body">
                            @if(count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li>
                                    @endforeach
                                    </ul>
                                </div>
                            @endif
                            @if(\Session::has('success'))
                                <div class="alert alert-success">
                                    <p>{{ \Session::get('success') }}</p>
                                </div>
                            @endif
    <form method="post" action="{{action('UserController@update', $id)}}">
        {{csrf_field()}}
        <input type="hidden" name="_method" value="PATCH" />
        <div class="form-group">
            <div><label for="">Type de l'utilisateur</label></div>
                <select name="user_type" class="form-control result">
                    <option value="particulier">Particulier</option>    
                    <option value="professionnel">Professionnel</option>                                        
                </select>
        </div>
        <div class="form-group">
            <label>Username</label><input type="text" name="username" class="form-control" value="{{$user->username}}" />
        </div>
        <div class="form-group">
            <label>Garage</label><input type="text" name="garage" class="form-control" value="{{$user->garage}}" />
        </div>
        <div class="form-group">
            <label>E-mail</label><input type="text" name="email" class="form-control" value="{{$user->email}}" />
        </div>
        <div class="form-group">
            <label>Prénom</label><input type="text" name="first_name" class="form-control" value="{{$user->first_name}}" />
        </div>
        <div class="form-group">
            <label>Nom</label><input type="text" name="last_name" class="form-control" value="{{$user->last_name}}" />
        </div>
        <div class="form-group">
            <label>Adresse</label><input type="text" name="adresse" class="form-control" value="{{$user->adresse}}" />
        </div>
        <div class="form-group">
            <label>Date de naissance</label><input type="text" name="birthdate" class="form-control" value="{{$user->birthdate}}" />
        </div>
        <div class="form-group">
            <label>Numéro de téléphone</label><input type="text" name="phone_number" class="form-control" value="{{$user->phone_number}}" />
        </div>
        <div class="form-group">
            <label>Fixe</label><input type="text" name="fixe" class="form-control" value="{{$user->fixe}}"/>
        </div>
        <div class="form-group">
            <label>Ville</label><input type="text" name="city" class="form-control" value="{{$user->city}}"/>
        </div>
        <div class="form-group">
            <label>Pays</label><input type="text" name="country" class="form-control" value="{{$user->country}}" />
        </div>
        <div class="form-group">
            <label>Code postal</label><input type="text" name="postal" class="form-control" value="{{$user->postal}}"/>
        </div>
        <div class="form-group">
            <label>Rating</label><input type="text" name="rating" class="form-control" value="{{$user->rating}}" />
        </div>
        <div class="form-group">
            <label>Type</label><input type="text" name="type" class="form-control" value="{{$user->type}}" />
        </div>
        <div class="form-group center">
            <input type="submit" class="btn btn-info pull-right" value="Submit" />
        </div>
        </form>
        <a href="javascript:history.back()" class="btn btn-primary">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
            </a>
        </div>
    </div>
</div>
</div>
</div>

@endsection

resources/views/administration/index.blade.php
@extends('home')

@section('style')
<style>
    th, td
    {
        text-align: center;
    }
</style>
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <br />
        
        
        <div class="InscriptionHeader" align="right">
            <a href="{{route('article.create')}}" class="btn btn-primary">Ajouter un article</a>
            <a href="{{route('brand.create')}}" class="btn btn-primary">Ajouter une marque</a>
            <a href="{{route('model.create')}}" class="btn btn-primary">Ajouter un modèle</a>
            <br />
        </div>
        <div class="InscriptionHeader" align="center">
        <h2 class="text-uppercase m-b-10">Users</h2>
        </div>
        <table class="table">
                <tr class="thead-dark">
                    <th>E-mail</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Numéro de téléphone</th>
                    <th>Type</th>
                    <th>Statut</th>
                    <th>Note</th>
                    <th>Dernière connexion</th>
                    <th>Date de création</th>
                    <th>Actions</th>
                </tr>
                @foreach($users as $row)
                <tr style="background-color:#FFFF;">
                    <td>{{ $row['email']}}</td> 
                    <td>{{ $row['first_name']}}</td> 
                    <td>{{ $row['last_name']}}</td> 
                    <td>{{ $row['phone_number']}}</td> 
                    <td>
                        @if($row->type==1)
                        <strong>Admin</strong>
                        @else
                        User
                        @endif
                    </td> 
                    <td>
                        @if($row->is_active==1)
                        <b style="color:green;">Active</b>
                        @else
                        <b style="color:red;">Inactive</b>
                        @endif
                    </td> 
                    <td>{{ $row['rating']}}</td> 
                    <td>{{ $row['last_login']}}</td>
                    <td>{{ $row['created_at']}}</td>
                    <td width="25%">
                            <a style="display:inline;" href="{{action('UserController@edit', $row['id'])}}"><span class="btn btn-outline-success ">&Eacute;diter</span></a>
                            <form style="display:inline;" method="post" class="delete_form" action="{{action('UserController@destroy', $row['id'])}}">
                                    {{csrf_field()}}
                                    <input type="hidden" name="_method" value="DELETE" />
                                    <button type="submit" class="btn btn-outline-danger">Supprimer</button>
                            </form>
                            <a href="/administration/active/{{$row->id}}/finished" class="btn btn-outline-info">Changer le statut</a>
                        </span>
                    </td>
                </tr>
                @endforeach
        </table>
        {{ $users->links() }}
    </div>
</div>
@endsection

@section('script')
<script>
        $(document).ready(function(){
         $('.delete_form').on('submit', function(){
          if(confirm("Are you sure you want to delete it?"))
          {
           return true;
          }
          else
          {
           return false;
          }
         });
        });
</script>
@endsection