routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
Route::get('/', 'HomeController@index')->name('home');

//Api Ajax
Route::post('/api/vehicles/count', 'ApiController@getNbOfVehicles');
Route::post('/api/vehicles/estim', 'ApiController@estimVehicles');
Route::post('/api/vehicles/formulaires', 'ApiController@formulaires');
Route::get('/api/brand/byType/{type}/{neuf}', 'ApiController@brandByType');
Route::post('/api/comments/store', 'CommentController@store');
Route::get('/api/comments/exprension/{exp}/{id}', 'CommentController@exprension');
Route::get('/api/vehicles/comparateurVehicles/{model}', 'ApiController@getcomparateurVehicles');

//Search Routes
Route::post('/search/searchNeuf', "searchController@searchNeuf");
Route::post('/search/guide_search', "searchController@searchNeuf");
Route::post('/search/searchOccasion', "searchController@searchOccasion");
Route::get('/search/searchOccasion', "searchController@searchOccasion"); // pagination
Route::get('/search/neuf/{brand}', "searchController@searchNeufBrand");
Route::get('/search/neuf/{brand}/{model}', "searchController@searchNeufModel");
Route::get('/search/searchDetailed', "searchController@searchDetailed");
Route::get('/search/searchDetailedOccasion', "searchController@searchDetailedOccasion");

//Routes Neuf
Route::get('/neuf', 'NeufController@index');
Route::post('/neuf/comparateur', 'NeufController@comparateur');
Route::get('/neuf/{brand}', 'NeufController@brand');
Route::get('/neuf/{brand}/{model}', 'NeufController@model');
Route::get('/neuf/{brand}/{model}/{version}', 'NeufController@version');

//Route Occasion
Route::get('/occasion', 'OccasionController@index');
Route::get('/occasion/annonce/{{id}}', 'OccasionController@index');

//Route Partenaire
Route::resource('/partenaires', 'PartenaireController');

//Route Video
Route::get('/videos', 'VideoController@allVideos');
Route::get('/videos/brand/{brandname}', 'VideoController@videosBySelect');
Route::get('/videos/{id}', 'ArticleController@show');

//Routes article
Route::get('/articles', 'ArticleController@allArticles');
Route::get('/articles/cat/{catname}', 'ArticleController@articlesByCat');
Route::get('/articles/{id}', 'ArticleController@showArticle');

// Routes administration
Route::resource('/administration/video', 'VideoController');
Route::resource('/administration/article', 'ArticleController');
Route::resource('/administration/brand', 'BrandController');
Route::resource('/administration/model', 'ModeleController');

Route::get('/administration/comment', 'CommentController@index');
//Route::get('/administration/comment/cmntSupp', 'CommentController@cmntSupp');
Route::get('/administration/comment/accepter/{id}', 'CommentController@accepter');
Route::get('/administration/comment/supprimer/{id}', 'CommentController@destroy');
Route::get('/administration/active/{id}/finished', 'UserController@active');

Route::resource('/administration/categorie', 'CategorieArticleController');
Route::resource('/administration', 'UserController');

app/Http/Controllers/NeufController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Promotion;
use App\Brand;
use App\Energie;
use App\Modele;
use App\Vehicle;
use App\Video;
use App\Article;

class NeufController extends Controller
{
    public function index(){
        session()->flush();
        $promotions = Vehicle::where('isNeuf', 1)
                                ->whereHas('promotions', function ($query) {
                                    $query->where('start_at', '<=', gmdate("Y-m-d H:s:i"))
                                        ->where('end_at', '>=', gmdate("Y-m-d H:s:i"));
                                })
                                ->with(['modele.brand', 'promotionLast'])
                                ->limit(10)
                                ->get();
        $brands = Brand::whereHas('modeles', function ($query) {
                            $query->whereHas('vehicles', function ($query) {
                                $query->where('isNeuf', 1)
                                        ->where('status', 1);
                            });
                        });
        $brands = $brands->withCount(['modeles' => function ($query) {
                                $query->whereHas('vehicles', function ($query) {
                                    $query->where('isNeuf', 1)
                                        ->where('status', 1);
                                });
                            }])
                            ->get();
        $articles = Article::whereIn('brand_id',$brands->pluck('id'))->limit(10)->get();
        return view('neuf.byBrand')
            ->withBrands($brands)
            ->withArticles($articles)
            ->withPromotions($promotions);    
    }
    
    public function brand($slugBrand){
        session()->flush();
        $brand = Brand::where("slug", $slugBrand)->first();
        $modeles = $brand->modeles()
                            ->whereHas('vehicles', function ($query) {
                                $query->where('isNeuf', 1)
                                        ->where('status', 1);
                            });
        $modeles = $modeles->withCount(['vehicles' => function ($query) {
                                $query->where('isNeuf', 1)->where('status', 1);
                            }])
                            ->with('minPrix')
                            ->get();
        $promotions = Vehicle::where('isNeuf', 1)
                                ->whereIn('model_id',$modeles->pluck('id'))
                                ->whereHas('promotions', function ($query) {
                                    $query->where('start_at', '<=', gmdate("Y-m-d H:s:i"))
                                    ->where('end_at', '>=', gmdate("Y-m-d H:s:i"));
                                })
                                ->where('status', 1)
                                ->with(['modele.brand', 'promotionLast'])
                                ->limit(10)
                                ->get();
        $articles = Article::whereIn('model_id',$modeles->pluck('id'))->limit(10)->get();

        return view('neuf.byModel')
            ->withBrand($brand)
            ->withArticles($articles)
            ->withModeles($modeles)
            ->withPromotions($promotions);  
    }

    public function model($slugBrand, $slugModel){
        session()->flush();
        $input['energy'] = 0;
        $energies = Energie::all();
        $brand = Brand::where("slug", $slugBrand)->first();
        $model = Modele::where("slug", $slugModel)->with('minPrix')->first();
        $vehicles = $model->vehicles()
                            ->where('isNeuf', 1)
                            ->where('status', 1)
                            ->with('medias')
                            ->get();
        $articles = Article::where('model_id',$model->id)->limit(10)->get();
        $promotions = Vehicle::where('isNeuf', 1)
                                ->where('model_id',$model->id)
                                ->whereHas('promotions', function ($query) {
                                    $query->where('start_at', '<=', gmdate("Y-m-d H:s:i"))
                                    ->where('end_at', '>=', gmdate("Y-m-d H:s:i"));
                                })
                                ->where('status', 1)
                                ->with(['modele.brand', 'promotionLast'])
                                ->limit(10)
                                ->get();
        return view('neuf.byVersion')->withInput($input)
            ->withBrand($brand)
            ->withArticles($articles)
            ->withVehicles($vehicles)
            ->withEnergies($energies)
            ->withModel($model)
            ->withPromotions($promotions);
    }

    public function version($slugBrand, $slugModel, $slugVersion){
        $brand = Brand::where("slug", $slugBrand)->first();
        $model = Modele::where("slug", $slugModel)->first();
        $version = Vehicle::where("slug", $slugVersion)->with('energie')->first();
        $promotions = Vehicle::where('isNeuf', 1)
                        ->where('model_id',$model->id)
                        ->whereHas('promotions', function ($query) {
                            $query->where('start_at', '<=', gmdate("Y-m-d H:s:i"))
                            ->where('end_at', '>=', gmdate("Y-m-d H:s:i"));
                        })
                        ->where('status', 1)
                        ->with(['modele.brand', 'promotionLast'])
                        ->limit(10)
                        ->get();
        $rcPricemin = $version->price * 0.75;
        $rcPricemax = $version->price * 1.25;
        $recommendations = Vehicle::whereBetween('price',[$rcPricemin, $rcPricemax])
                                    ->where('isNeuf', 1)
                                    ->where('status', 1)
                                    ->with('modele.brand')
                                    ->get();
        // refaire
        $videos = $brand->videos()->get();
        $articles = Article::where('model_id',$model->id)->limit(10)->get();        
        return view('neuf.version')->withBrand($brand)
                                    ->withModel($model)
                                    ->withPromotions($promotions)
                                    ->withRecommendations($recommendations)
                                    ->withVersion($version)
                                    ->withArticles($articles)
                                    ->withVideos($videos)
                                    ;
    }

    public function comparateur(Request $request){
        $version1 = Vehicle::find($request->version1);
        $version2 = Vehicle::find($request->version2);
        return view('neuf.comparateur')->withVersion1($version1)->withVersion2($version2);
    }
}

resources/views/neuf/byBrand.blade.php
@extends('layouts.app')
@section('title', 'Toutes les marques')
@section('style')
<style>
.brandWidth {
    max-height: 82px;
    width: auto !important;
}
</style>
@endsection
@section('content')
<section class="PreBd m-t-30">
    <div class="container">
        <div class="section-block section-block-white HasPadding">
            <div class="row">
                <div class="Breadcrumps col-md-12 m-t-10">
                    <ul>
                        <li><a href="{{ url('/') }}">Accueil</a></li>
                        <li><a href="{{ url('/neuf') }}" class="text-capitalize">@if(isset($input['type'])){{$input['type']}}s @else véhicules @endif neuves</a></li>
                        <li><a href="#" class="active">Toutes les marques</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-9">
                    <div class="AutoRM-container m-t-15">
                        <div class="row m-0">
                            @foreach ($brands as $brand)
                                @if($brand->modeles_count >0)
                                <div class="col-md-3">
                                    <article class="AutoRM-Box AutoRM-DIV-Brand">
                                        <div class="AutoRM-Thumb ">
                                            @if(Session::has('brand'))
                                                <a class="brResult" href="{{url('/search/neuf')}}/{{$brand->slug}}"><img class="brandWidth" src="{{ $brand->logo }}" alt=""></a>
                                            @else
                                                <a class="brResult" href="{{url('/neuf')}}/{{$brand->slug}}"><img class="brandWidth" src="{{ $brand->logo }}" alt=""></a>
                                            @endif
                                        </div>
                                        <div class="AutoRM-Body">
                                            <h4>{{ $brand->name}}</h4>
                                            <span class="AutoRM-Version">{{ $brand->modeles_count }} @if($brand->modeles_count > 1)modèles disponibles @else modèle disponible @endif  </span>
                                        </div>
                                    </article>
                                </div>
                                @endif  
                            @endforeach   
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <aside class="Sidebar">
                        @if(sizeof($promotions))
                        <div class="Widget WidgetWhite">
                            <div class="WidgetBanner">Offres spéciales</div>
                            <div class="Offre-spe owl-carousel owl-theme">
                        
                                @foreach ($promotions as $promotion)
                                    <div class="CP-Box text-center">
                                        <a href="{{url('/neuf')}}/{{$promotion->modele->brand->slug}}/{{$promotion->modele->slug}}/{{$promotion->slug}}">
                                            <div class="CP-Box-Thumb">
                                                <img src="{{$promotion->image}}" alt="{{$promotion->name}}">
                                            </div>
                                            <div class="CP-Box-Body">
                                                <h5 class="CP-Box-Title">{{$promotion->name}}</h5>
                                                <span class="CP-des">{{$promotion->promotionLast[0]->description}}</span>
                                                <span class="CD-Prox-span">Jusqu'à <strong>-{{$promotion->promotionLast[0]->percentage}}</strong></span>
                                            </div>
                                        </a>
                                    </div>
                                @endforeach  

                            </div>
                        </div>
                        @endif
                        @if(sizeof($articles))
                        <div class="Widget WidgetWhite">
                            <div class="WidgetBanner">Dernières ACTUS des marques</div>
                            <div class="ActuListing">
                                <ul>
                                    @foreach($articles as $article)
                                        <li><a href="{{url('/articles')}}/{{$article->slug}}-{{$article->id}}">{{substr($article->title,0,50)}}...</a></li>
                                    @endforeach
                                </ul>
                                <a href="{{url('/articles')}}" class="text-right actu-more">Voir toutes les actus</a>
                            </div>
                        </div>
                        @endif
                        <div class="Widget WidgetWhite">
                            <img src="{{ asset('/img/corbeille/ads-1.jpg') }}">
                        </div>
                    </aside>
                </div>
            </div>

        </div>
    </div>
</section>
@endsection

resources/views/neuf/byModel.blade.php
@extends('layouts.app')
@section('title',$brand->name.'- Modèles')

@section('content')
<section class="PreBd m-t-30">	
	<div class="container">
        <div class="section-block section-block-white HasPadding">            
            <div class="row">
                <div class="Breadcrumps col-md-12 m-t-10">
                    <ul>
                        <li><a href="{{url('/')}}">Accueil</a></li>
                        <li><a href="{{url('/neuf')}}">Voitures neuves</a></li>
                        <li><a href="{{url('/neuf/')}}{{$brand->slug}}">{{$brand->name}}</a></li>
                    </ul>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-9">
                    <div class="row">

                        <div class="col-md-12">
                            <div class="AutoBrandWrapper m-t-20 m-b-10">
                                <div class="float-left"><img src="{{$brand->logo}}" alt="{{$brand->name}}"> </div>
                                <span>{{$brand->name}}</span>
                            </div>

                            <p>{{$brand->description}}</p>
                        </div>

                    </div>

                    <h3 class="m-t-20 Title-Lis-bn">{{$brand->name}} - Modèles</h3>

                    <div class="AutoRM-container m-t-15">

                        <div class="row m-0">
                        @if(sizeof($modeles)!=0)
                            @foreach ($modeles as $model)
                                @if($model->vehicles_count > 0)
                                    <div class="col-md-4 ">
                                        <div class="AutoRM-DIV">
                                            @if(Session::has('brand'))
                                            <a class="mdResult" href="{{url('/search/neuf')}}/{{$brand->slug}}/{{$model->slug}}">
                                            @else
                                            <a class="mdResult" href="{{url('/neuf')}}/{{$brand->slug}}/{{$model->slug}}">
                                            @endif
                                            <article class="AutoRM-Box">
                                                <div class="AutoRM-Thumb">
                                                    <div style=" position: relative; overflow: hidden;"><img src="{{ $model->image }}" alt="" class="zoom"></div>
                                                </div>
                                                <div class="AutoRM-Body">
                                                    <h4>{{ $model->name}}</h4>
                                                    <span class="AutoRM-Version">{{ $model->vehicles_count }}  @if($model->vehicles_count > 1) versions disponibles @else version disponible @endif </span>
                                                    @if($model->minPrix->first())
                                                    <span class="AutoRM-Price">&Agrave; partir de {{$model->minPrix->first()['price'] }} DH</span>
                                                    @endif
                                                </div>
                                            </article>
                                            </a>
                                        </div>
                                    </div>
                                @endif	
                            @endforeach	
                        @endif	

                        </div>

                    </div>

                </div>

                <div class="col-md-3">
                <aside class="Sidebar">

                    @if(sizeof($promotions))
                        <div class="Widget WidgetWhite">
                            <div class="WidgetBanner">Offres spéciales</div>
                            <div class="Offre-spe owl-carousel owl-theme">
                        
                                @foreach ($promotions as $promotion)
                                    <div class="CP-Box text-center">
                                        <a href="{{url('/neuf')}}/{{$promotion->modele->brand->slug}}/{{$promotion->modele->slug}}/{{$promotion->slug}}">
                                            <div class="CP-Box-Thumb">
                                                <img src="{{$promotion->image}}" alt="{{$promotion->name}}">
                                            </div>
                                            <div class="CP-Box-Body">
                                                <h5 class="CP-Box-Title">{{$promotion->name}}</h5>
                                                <span class="CP-des">{{$promotion->promotionLast[0]->description}}</span>
                                                <span class="CD-Prox-span">Jusqu'à <strong>-{{$promotion->promotionLast[0]->percentage}}</strong></span>
                                            </div>
                                        </a>
                                    </div>
                                @endforeach  
                                
                        </div>
                    @endif
                    @if(sizeof($articles))
                        <div class="Widget WidgetWhite">
                            <div class="WidgetBanner">Dernières ACTUS {{$brand->name}}</div>
                            <div class="ActuListing">
                                <ul>
                                    @foreach($articles as $article)
                                        <li><a href="{{url('/articles')}}/{{$article->slug}}-{{$article->id}}">{{substr($article->title,0,50)}}...</a></li>
                                    @endforeach
                                </ul>
                                <a href="{{url('/articles')}}" class="text-right actu-more">Voir toutes les actus</a>
                            </div>
                        </div>
                    @endif

                    <div class="Widget WidgetWhite">
                        <img src="{{ asset('/img/corbeille/ads-1.jpg') }}">
                    </div>

                </aside>
                </div>

            </div>
            
		</div>
	</div>	
</section>
@endsection

resources/views/neuf/comparateur.blade.php
@extends('layouts.app')
@section('content')
<section class="PreBd m-t-30">
	<div class="container">
        <div class="section-block section-block-white HasPadding">
            <div class="row">
                <div class="Pagesheader color-theme col-md-12">
                    <h2 class="text-uppercase">Comparateur</h2>
                </div>
                <div class="Breadcrumps col-md-12">
                    <ul>
                        <li><a href="{{url('/')}}">Accueil</a></li>
                        <li><a href="{{url('/neuf/comparateur')}}">Comparateur</a></li>
                    </ul>
                </div>
            </div>
            <input type="text" id="versionId">
            <button class="btn btn-blue" id="ajouterComp">Ajouter</button>
            <input type="hidden" value="{{$version1}}">
            <input type="hidden" value="{{$version2}}">
            <div class="row col-md-12 m-t-20" id="affComp">
                <div class="col-md-6">{!! str_replace(',"','<br />"',$version1) !!}</div>
                <div class="col-md-6">{!! str_replace(',"','<br />"',$version2) !!}</div>
            </div>
        </div>
	</di
</section>            
@endsection
@section('script')
<script>
    $('#ajouterComp').click(function () {
        console.log($('#affComp col-md-*'));
        
    });
</script>
@endsection